In [9]:
# Load libraries
from sklearn.neural_network import MLPClassifier
from sklearn import metrics

In [10]:
from keras.datasets import mnist

In [11]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [12]:
#Anzeigen, wie die Daten vorliegen (Trainings- und Testdaten mit Pixelnanzahl)
print('X_train: ' + str(X_train.shape))
print('Y_train: ' + str(y_train.shape))
print('X_test:  '  + str(X_test.shape))
print('Y_test:  '  + str(y_test.shape))

X_train: (60000, 28, 28)
Y_train: (60000,)
X_test:  (10000, 28, 28)
Y_test:  (10000,)


In [13]:
# Bilder in Vektoren umformen
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]) 
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1]*X_test.shape[2]) 

In [14]:
# Überprüfung ob Umformung funktioniert hat
print("Number of training examples :", X_train.shape[0], "and each image is of shape (%d)"%(X_train.shape[1]))
print("Number of training examples :", X_test.shape[0], "and each image is of shape (%d)"%(X_test.shape[1]))

Number of training examples : 60000 and each image is of shape (784)
Number of training examples : 10000 and each image is of shape (784)


In [15]:
#Normalisierung der Daten
X_train = X_train/255
X_test = X_test/255

In [72]:
lbfgs = MLPClassifier(solver='lbfgs', alpha=1, hidden_layer_sizes=(784, 10), random_state=1, max_iter=1000)
#adam = MLPClassifier(solver='adam', alpha=1, hidden_layer_sizes=(50, 50, 20), random_state=1, max_iter=200)
#sgd = MLPClassifier(solver='sgd', alpha=1, hidden_layer_sizes=(50, 50, 20), random_state=1, max_iter=200)

In [73]:
lbfgs = lbfgs.fit(X_train,y_train)
#adam = adam.fit(X_train,y_train)
#sgd = sgd.fit(X_train,y_train)

In [74]:
y_pred1 = lbfgs.predict(X_test)
#y_pred2 = adam.predict(X_test)
#y_pred3 = sgd.predict(X_test)

In [75]:
print("Accuracy lbfgs:", metrics.accuracy_score(y_test, y_pred1))
#print("Accuracy adam:", metrics.accuracy_score(y_test, y_pred2))
#print("Accuracy sgd:", metrics.accuracy_score(y_test, y_pred3))

Accuracy lbfgs: 0.9792


In [76]:
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [79]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred1)

array([[ 968,    0,    0,    1,    1,    1,    5,    1,    3,    0],
       [   0, 1127,    1,    2,    0,    0,    1,    1,    3,    0],
       [   2,    0, 1009,    2,    5,    0,    2,    5,    6,    1],
       [   0,    0,    5,  987,    0,    5,    0,    6,    5,    2],
       [   1,    0,    5,    0,  963,    0,    2,    2,    0,    9],
       [   2,    0,    0,   10,    1,  869,    5,    1,    3,    1],
       [   4,    2,    0,    1,    7,    4,  936,    0,    4,    0],
       [   1,    1,    9,    3,    1,    0,    0, 1007,    2,    4],
       [   2,    1,    2,    9,    1,    5,    2,    2,  946,    4],
       [   3,    3,    0,    3,   14,    1,    0,    2,    3,  980]])

In [78]:
confusion_matrix(y_test, y_pred2)

array([[ 969,    0,    0,    0,    1,    0,    5,    1,    4,    0],
       [   0, 1123,    2,    2,    0,    0,    3,    2,    3,    0],
       [   8,    0, 1003,    5,    3,    0,    3,    8,    2,    0],
       [   0,    0,    7,  990,    0,    0,    0,    7,    3,    3],
       [   2,    0,    5,    0,  946,    0,    4,    1,    2,   22],
       [   4,    1,    0,   13,    0,  848,   11,    1,    6,    8],
       [   4,    3,    1,    0,   13,    3,  929,    0,    5,    0],
       [   2,    7,   14,    7,    2,    0,    0,  983,    0,   13],
       [   5,    0,    6,   13,    4,    4,    5,    2,  927,    8],
       [   5,    4,    1,    7,    8,    2,    0,    4,    1,  977]])

In [43]:
confusion_matrix(y_test, y_pred3)

array([[ 960,    0,    4,    0,    1,    7,    3,    4,    1,    0],
       [   0, 1111,    2,    5,    0,    0,    3,    2,   12,    0],
       [  14,    8,  938,   10,    5,    0,   18,   19,   18,    2],
       [   2,    1,   25,  923,    0,   31,    0,   14,    9,    5],
       [   4,    4,    3,    0,  902,    0,   15,    3,   10,   41],
       [  13,    1,    5,   49,    5,  785,    7,    0,   16,   11],
       [  10,    4,    5,    0,   10,   10,  912,    2,    5,    0],
       [   3,   11,   17,   10,    4,    0,    0,  962,    0,   21],
       [   6,    8,   12,    8,   12,   13,    8,    6,  891,   10],
       [   8,    8,    1,    8,   29,    7,    0,   12,    6,  930]])